POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2NGY4NTVjOTk4YTQ3MDY2NjkyOGNiMiIsImlhdCI6MTcxNjQ5ODUxOX0.rPtAA4eCmGKTAPNYgaUiRW7tnNVActDnDfXOqolk6xE

{
    "title": "user blog 2",
    "url": "lovestolaugh.com",
    "likes": 121
}